name: pull-pluginmd-from-external-repo
# on:
#   issues:
#     types: [opened]
on: 
  workflow_dispatch:
    inputs:
      owner:
        description: Repo owner
        required: true
      repo:
        description: Repo name
        required: true
      branch:
        description: branch name
        default: master
        required: false
jobs:
  pull-readme-md:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pull file
        run: |
          git clone https://github.com/yasasw/vue-demo-page.git
          cp -r vue-demo-page/plugins/ plugins
          rm -r vue-demo-page
          cd plugins
          wget https://raw.githubusercontent.com/Duet3D/DuetSoftwareFramework/master/README.md -O DuetSoftwareFramework.md
        #  cd ../
        # git config --global user.name "yasasw"
          # git config --global user.email "yasas.wijetilake@gmail.com"
          # git clone https://github.com/yasasw/vue-demo-page.git
          # cp -r vue-demo-page/src/plugins/ plugins
          # rm -r vue-demo-page
          # cd plugins
          # wget https://raw.githubusercontent.com/Duet3D/DuetSoftwareFramework/master/README.md -O DuetSoftwareFramework.md
          # cd ../
      - name: push to another repo
        id: push_file
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: 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
        with:
          source-directory: ./
          destination-github-username: 'yasasw'
          destination-repository-name: 'vue-demo-page'
          user-email: yasas.wijetilake@gmail.com
          commit-message: Something
          target-branch: master
      #----------------------------------------------------------------------------------------------------------------------------
      # - uses: actions/checkout@v3
      # - name: Setup Git
      #   env:
      #     API_TOKEN_GITHUB: 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
      #   run: |
      #     git config --global user.name "yasasw"
      #     git config --global user.email "yasas.wijetilake@gmail.com"
      #     git clone --single-branch --branch master https://yasas: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@github.com/yasasw/vue-demo-page.git
      #     cd vue-demo-page
      #     cd src/plugins
      #     wget https://raw.githubusercontent.com/Duet3D/DuetSoftwareFramework/master/README.md
      #     cd ../../
      #     git add .
      #     git commit -m "Add file"
      #     git push https://yasas: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@github.com/yasasw/vue-demo-page.git --set-upstream master 
      #----------------------------------------------------------------------------------------------------------------------------
      # - name: Create Pull Request
      #   uses: peter-evans/create-pull-request@v4
      #   with:
      #     token: ${{ secrets.DEPLOY_SECRET }}
      #     commit-message: New Plugin
      #     committer: GitHub <noreply@github.com>
      #     author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
      #     signoff: false
      #     branch: plugin-timestamp
      #     delete-branch: false
      #     title: '[Example] Update report'
      #     body: |
      #       Update report
      #       - Updated with *today's* date
      #       - Auto-generated by [create-pull-request][1]

      #     labels: |
      #       report
      #       automated pr
      #     assignees: yasasw
      #     reviewers: yasasw
      #     team-reviewers: |
      #       owners
      #       maintainers
      #     milestone: 1
      #     draft: false
    # steps:
    # - uses: actions/checkout@v2
    # - name: Run script file
    #   run: |
    #      chmod +x ./.github/workflows/script.sh
    #      ./.github/workflows/script.sh ${{ secrets.DEPLOY_SECRET }} ${{ github.event.inputs.PluginAuthor }} ${{ github.event.inputs.PluginRepo }} ${{ github.event.inputs.PluginBranch }}
    # - name: Run script file
    #   run: |
    #      chmod +x ./.github/workflows/script.sh
    #      ./.github/workflows/script.sh ${{ secrets.DEPLOY_SECRET }} ${{ github.event.inputs.owner }} ${{ github.event.inputs.repo }} ${{ github.event.inputs.branch }}