name: pull-pluginmd-from-external-repo
# on:
#   issues:
#     types: [opened]
on: 
  workflow_dispatch:
    inputs:
      owner:
        description: Repo owner
        required: true
      repo:
        description: Repo name
        required: true
      branch:
        description: branch name
        default: master
        required: false
jobs:
  pull-readme-md:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pull file
        run: |
          echo test 
          echo $(ls -a)
          cd src/plugins 
          wget https://raw.githubusercontent.com/Duet3D/DuetSoftwareFramework/master/README.md -O DuetSoftwareFramework555.md
          git config --global user.name "yasasw"
          git config --global user.email "yasas.wijetilake@gmail.com"
          git checkout -b submission/WK24DuetSoftwareFramework
          git add DuetSoftwareFramework555.md
          git commit -m "Updating plugin"
          git push -u origin submission/WK24DuetSoftwareFramework

        #git push -u origin master
      # - name: Create Pull Request
      #   uses: peter-evans/create-pull-request@v4
      #   with:
      #     token: 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
      #     commit-message: New Plugin
      #     committer: yasasw <yasas.wijetilake@gmail.com>
      #     author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
      #     signoff: false
      #     branch: plugin-timestamp
      #     delete-branch: false
      #     title: '[Example] Update report'
      #     body: |
      #       Update report
      #       - Updated with *today's* date
      #       - Auto-generated by [create-pull-request][1]

      #     labels: |
      #       report
      #       automated pr
      #     assignees: yasasw
      #     reviewers: yasasw
      #     team-reviewers: |
      #       owners
      #       maintainers
      #     milestone: 1
      #     draft: false