name: pull-pluginmd-from-external-repo
# on:
#   issues:
#     types: [opened]
on: 
  workflow_dispatch:
    inputs:
      PluginAuthor:
        description: Repo owner
        required: true
      PluginRepo:
        description: Repo name
        required: true
      PluginBranch:
        description: Branch name
        default: master
        required: false
      PluginTitle:
        description: Plugin title
        required: true
      PluginAbstract:
        description: Summary
        required: true
      IsOEM:
        description: is plugin OEM
        required: false
      PluginTags:
        description: Plugin tags/keywords
        required: true
jobs:
  pull-readme-md:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch and create PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo test 
          echo $(ls -a)
          echo ${{ github.event.inputs.repo }}
          branchName=submission/$(date +"%y%m%d")$PluginRepo
          commituser=yasasw

          cd src/plugins 

          wget https://raw.githubusercontent.com/${{ github.event.inputs.PluginAuthor }}/${{ github.event.inputs.PluginRepo }}/${{ github.event.inputs.PluginBranch }}/README.md -O ${{ github.event.issue.PluginRepo }}.md
          
          git config --global user.name "yasasw"
          git config --global user.email "yasas.wijetilake@gmail.com"
          git checkout -b $branchName
          git add ${{ github.event.issue.PluginRepo }}.md
          git commit -m "Updating plugin ${{ github.event.issue.PluginRepo }}.md"
          git push -u origin $branchName

          hub pull-request -m "$branchName" --base $commituser:master --head $commituser:$branchName