name: pull-pluginmd-from-external-repo
# on:
#   issues:
#     types: [opened]
on: 
  workflow_dispatch:
    inputs:
      owner:
        description: Repo owner
        required: true
      repo:
        description: Repo name
        required: true
      branch:
        description: branch name
        default: master
        required: false
jobs:
  pull-readme-md:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch the file and create PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo test 
          echo $(ls -a)
          echo ${{ github.event.repo }}
          cd src/plugins 
          branchName=feature/WKDuet3D
          wget https://raw.githubusercontent.com/${{ github.event.issue.PluginAuthor }}/${{ github.event.issue.PluginRepo }}/master/README.md -O ${{ github.event.issue.PluginRepo }}.md
          git config --global user.name "yasasw"
          git config --global user.email "yasas.wijetilake@gmail.com"
          git checkout -b $branchName
          git add DuetSoftwareFramework555.md
          git commit -m "Updating plugin"
          git push -u origin $branchName

          hub pull-request -m "WK24DuetSoftwareFramework3" --base yasasw:master --head yasasw:$branchName