name: pull-pluginmd-from-external-repo
# on:
#   issues:
#     types: [opened]
on: 
  workflow_dispatch:
    inputs:
      owner:
        description: Repo owner
        required: true
      repo:
        description: Repo name
        required: true
      branch:
        description: branch name
        default: master
        required: false
jobs:
  pull-readme-md:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Git
        run: |
          git config --global user.name "yasasw"
          git config --global user.email "yasas.wijetilake@gmail.com"
          git clone https://github.com/yasasw/vue-demo-page.git
          cd vue-demo-page
          cd src/plugins
          wget https://raw.githubusercontent.com/Duet3D/DuetSoftwareFramework/master/README.md
          git add -A
          git commit -m "Add file"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.DEPLOY_SECRET }}
          commit-message: New Plugin
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: plugin-timestamp
          delete-branch: false
          title: '[Example] Update report'
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]

          labels: |
            report
            automated pr
          assignees: yasasw
          reviewers: yasasw
          team-reviewers: |
            owners
            maintainers
          milestone: 1
          draft: false
    # steps:
    # - uses: actions/checkout@v2
    # - name: Run script file
    #   run: |
    #      chmod +x ./.github/workflows/script.sh
    #      ./.github/workflows/script.sh ${{ secrets.DEPLOY_SECRET }} ${{ github.event.inputs.PluginAuthor }} ${{ github.event.inputs.PluginRepo }} ${{ github.event.inputs.PluginBranch }}
    # - name: Run script file
    #   run: |
    #      chmod +x ./.github/workflows/script.sh
    #      ./.github/workflows/script.sh ${{ secrets.DEPLOY_SECRET }} ${{ github.event.inputs.owner }} ${{ github.event.inputs.repo }} ${{ github.event.inputs.branch }}