name: pull-pluginmd-from-external-repo
on:
  issues:
    types: [opened]
# on: 
#   workflow_dispatch:
#     inputs:
#       owner:
#         description: Repo owner
#         required: true
#       repo:
#         description: Repo name
#         required: true
#       branch:
#         description: branch name
#         default: master
#         required: false
jobs:
  pull-readme-md:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: |
         chmod +x ./.github/workflows/script.sh
         ./.github/workflows/script.sh ${{ secrets.DEPLOY_SECRET }} ${{ github.event.inputs.owner }} ${{ github.event.inputs.repo }} ${{ github.event.inputs.branch }}